name: powergen_edu
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Additional dependencies
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  change_app_package_name: ^1.4.0
  fl_chart: ^0.66.2
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5
  flutter_widget_from_html: ^0.16.0
  shared_preferences: ^2.5.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.3
  file_picker: ^10.1.2
  firebase_storage: ^12.4.5
  permission_handler: ^12.0.0+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/data/
    - assets/icon/
    - assets/images/bab1/
    - assets/images/bab2/
    - assets/images/bab3/
