name: powergen_edu
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  flutter_bloc: ^8.1.6
  change_app_package_name: ^1.4.0
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
